[[colors.indexed_colors]]
color = "#03697a"
index = 130

[colors.bright]
black = "#1b2e2e"
blue = "#3377ce"
cyan = "#4bcfcf"
green = "#3bc6c6"
magenta = "#36707a"
red = "#f07917"
white = "#d8d5bd"
yellow = "#ffaf2e"

[colors.normal]
black = "#030909"
blue = "#084a9e"
cyan = "#24c6c6"
green = "#00c1c1"
magenta = "#03697a"
red = "#ff5300"
white = "#c0bca0"
yellow = "#ff9e00"

[colors.primary]
background = "#040d1c"
foreground = "#fffce3"

[font]
size = 11.0

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"
